# Generated by Django 4.2.8 on 2024-01-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.TextField()),
                ('index_strike_price', models.IntegerField()),
                ('option_type', models.TextField()),
                ('expiry', models.TextField()),
                ('entry_start_price', models.IntegerField()),
                ('entry_end_price', models.IntegerField()),
                ('exit_first_target_price', models.IntegerField()),
                ('exit_second_target_price', models.IntegerField()),
                ('exit_third_target_price', models.IntegerField()),
                ('exit_stop_loss_price', models.IntegerField()),
                ('created_at_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.TextField()),
                ('text', models.TextField()),
                ('created_at_time', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['created_at_time'], name='trading_tel_created_147ebe_idx')],
            },
        ),
    ]
