# Generated by Django 4.2.8 on 2024-01-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtrade',
            name='entry_end_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='telegramtrade',
            name='exit_second_target_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='telegramtrade',
            name='exit_third_target_price',
            field=models.IntegerField(null=True),
        ),
    ]
