# Generated by Django 4.2.8 on 2024-01-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_telegramtrade_entry_end_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtrade',
            name='order_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramtrade',
            name='order_status',
            field=models.TextField(default='NOT_PLACED'),
            preserve_default=False,
        ),
    ]
