# Generated by Django 4.2.8 on 2024-01-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_telegramtrade_order_id_telegramtrade_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtrade',
            name='quantity',
            field=models.IntegerField(default=50),
        ),
    ]
