# Generated by Django 4.2.8 on 2024-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_telegramtrade_metadata_historicaltelegramtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='historicaltelegramtrade',
            name='entry_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='telegramtrade',
            name='entry_type',
            field=models.TextField(null=True),
        ),
    ]
