# Generated by Django 4.2.10 on 2024-03-31 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_combinedusertrade_userlogin_usertrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedusertrade',
            name='child_trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_trade', to='trading.combinedusertrade'),
        ),
        migrations.AddField(
            model_name='combinedusertrade',
            name='transaction_type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcombinedusertrade',
            name='child_trade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trading.combinedusertrade'),
        ),
        migrations.AddField(
            model_name='historicalcombinedusertrade',
            name='transaction_type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltelegramtrade',
            name='order_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='telegramtrade',
            name='order_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usertrade',
            name='combined_user_trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_trades', to='trading.combinedusertrade'),
        ),
    ]
