# Generated by Django 4.2.10 on 2024-04-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_combinedusertrade_child_trade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedusertrade',
            name='order_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcombinedusertrade',
            name='order_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalusertrade',
            name='order_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usertrade',
            name='order_id',
            field=models.TextField(null=True),
        ),
    ]
